### ISSUE TITLE
Allow site-level Web Profile settings

### ISSUE THREAD

**Issue by iversond** [psadmin-io/psadminio-io_portalwar#7]
The current configuration will set the Web Profile name for the sites in a domain. This should be set at the site-level so that each site can have it's own Web Profile.

**Comment by kbens** [comment]
I think this is the same for text.properties, etc. Should be site level, not domain.

In doing so, do we merge the hashes into the delivered `pia_domain_list:pia_sites`, versus stand alone `io_portalwar` hashes?

**Comment by kbens** [comment]
Tracking changes for this under [feature/site-support](https://github.com/psadmin-io/psadminio-io_portalwar/tree/feature/site-support) branch.

**Comment by kbens** [comment]
- [x] text.properties
- [x] configuration.properties
- [x] signonpage
~- [ ] favicons ???~
